const OrderData = [
  {
    id: "ORD-001",
    customerName: "John Smith",
    items: [
      { name: "Margherita", quantity: 2, price: 12.99 },
      { name: "Garlic Bread", quantity: 1, price: 5.99 },
    ],
    totalPrice: 31.97,
    paymentMethod: "credit_card",
    status: "pending",
    orderDate: "2024-01-08T10:30:00",
  },
  {
    id: "ORD-002",
    customerName: "Sarah Johnson",
    items: [
      { name: "Pepperoni", quantity: 1, price: 14.99 },
      { name: "Coke 2L", quantity: 1, price: 3.99 },
    ],
    totalPrice: 18.98,
    paymentMethod: "debit_card",
    status: "confirmed",
    orderDate: "2024-01-08T10:25:00",
  },
  {
    id: "ORD-003",
    customerName: "Mike Davis",
    items: [{ name: "Quattro Formaggi", quantity: 3, price: 15.99 }],
    totalPrice: 47.97,
    paymentMethod: "paypal",
    status: "preparing",
    orderDate: "2024-01-08T10:20:00",
  },
  {
    id: "ORD-004",
    customerName: "Emma Wilson",
    items: [
      { name: "BBQ Chicken", quantity: 1, price: 13.99 },
      { name: "Caesar Salad", quantity: 2, price: 6.99 },
      { name: "Tiramisu", quantity: 1, price: 5.99 },
    ],
    totalPrice: 33.96,
    paymentMethod: "credit_card",
    status: "ready",
    orderDate: "2024-01-08T10:15:00",
  },
  {
    id: "ORD-005",
    customerName: "James Brown",
    items: [{ name: "Vegetarian Supreme", quantity: 2, price: 13.99 }],
    totalPrice: 27.98,
    paymentMethod: "cash",
    status: "completed",
    orderDate: "2024-01-08T09:50:00",
  },
  {
    id: "ORD-006",
    customerName: "Lisa Anderson",
    items: [
      { name: "Meat Lovers", quantity: 1, price: 16.99 },
      { name: "Buffalo Wings", quantity: 1, price: 8.99 },
    ],
    totalPrice: 25.98,
    paymentMethod: "credit_card",
    status: "pending",
    orderDate: "2024-01-08T09:45:00",
  },
  {
    id: "ORD-007",
    customerName: "Robert Taylor",
    items: [{ name: "Spicy Italian", quantity: 1, price: 14.99 }],
    totalPrice: 14.99,
    paymentMethod: "debit_card",
    status: "confirmed",
    orderDate: "2024-01-08T09:40:00",
  },
  {
    id: "ORD-008",
    customerName: "Jennifer Lee",
    items: [
      { name: "Hawaiin", quantity: 2, price: 13.49 },
      { name: "Cheesy Dip", quantity: 2, price: 4.99 },
    ],
    totalPrice: 36.96,
    paymentMethod: "paypal",
    status: "preparing",
    orderDate: "2024-01-08T09:35:00",
  },
  {
    id: "ORD-009",
    customerName: "David Martinez",
    items: [{ name: "Deluxe Combo", quantity: 1, price: 24.99 }],
    totalPrice: 24.99,
    paymentMethod: "credit_card",
    status: "ready",
    orderDate: "2024-01-08T09:30:00",
  },
  {
    id: "ORD-010",
    customerName: "Amanda White",
    items: [{ name: "Classic Margherita", quantity: 3, price: 12.99 }],
    totalPrice: 38.97,
    paymentMethod: "cash",
    status: "completed",
    orderDate: "2024-01-08T09:20:00",
  },
]

export default OrderData;